# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_1:
    name: check code change
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: set up python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install python modules
        run: |
          python -m pip install --upgrade pip
          pip install watchdog
      - uses: technote-space/get-diff-action@v4
      
      - name: execute git diff
        run: |
          git diff --function-context HEAD^ HEAD > code_change
          value = 'cat code_change'
          echo ${value}
          
      - name: Set AFL++
        run: |
          git clone https://github.com/AFLplusplus/AFLplusplus.git AFLplusplus
          cd AFLplusplus
          make
          
      - name: target compile
        run: |
          cd test/cJSON
          CC=../../AFLplusplus/afl-cc make
      
      - name: seed selection
        run: 
          python getFuncName.py ./code_change ./test/cJSON/seed ./test/per_func_seed
      
      - name: run AFL++
        run: |
          python script.py -w ./test/cJSON -a ./AFLplusplus -x ./test/cJSON/cJSON_example -p ./new_seed_dir
